# docker-compose.dev.yml

services:
  app:
    image: catsay-dev:debian-12.1
    init: true
    volumes:
      - type: bind
        source: "."
        target: "/root/catsay"
    ports:
      - "4242:3000"
  redis:
    image: redis:7.2-alpine
